### PR TITLE
Payload 2023

### PR DESCRIPTION
**Pull request by Joe-Joe-Joe-Joe**
- Added support for Payload board copy IDs
- Added state estimation message types
- Added sensor ids for payload thermistors
- Commented out a couple definitions with conflict with the most up to date MPLAB system files

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/canlib/50)

### CODE REVIEW

**Review by KavinSatheeskumar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/canlib/50)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @Joe-Joe-Joe-Joe)

___
*[`message_types.h` line 27 at r1](https://reviewable.io/reviews/waterloo-rocketry/canlib/50#-NXwpdPI6XsU1Y-Uv9u7:-NXwpdPI6XsU1Y-Uv9u8:blakd7m) ([raw file](https://github.com/waterloo-rocketry/canlib/blob/f872ef10293cd4b558a120099ba72ae6873633ff/message_types.h#L27)):*
> ```objc
> #define MSG_DEBUG_RADIO_CMD       0x200
> 
> #define MSG_STATE_EST           0x300
> ```

This priority is pretty high, Zach suggested lowering it
___
*[`mcp2515/mcp_2515.h` line 124 at r1](https://reviewable.io/reviews/waterloo-rocketry/canlib/50#-NXwpP2q6xVzguaIzo1P:-NXwpP2q6xVzguaIzo1Q:b-2e52gb) ([raw file](https://github.com/waterloo-rocketry/canlib/blob/f872ef10293cd4b558a120099ba72ae6873633ff/mcp2515/mcp_2515.h#L124)):*
> ```objc
> 
> #define BFPCTRL   0x0C
> //#define TEC       0x1C
> ```

What is going on here? Why are you commenting

**Review by Darth-Raazi — APPROVED** [review]

**Review by KavinSatheeskumar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/canlib/50)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @Joe-Joe-Joe-Joe)

___
*[`can_common.c` line 409 at r2](https://reviewable.io/reviews/waterloo-rocketry/canlib/50#-NYBYAGH9BUdL1_93oiD:-NYBYAGH9BUdL1_93oiE:b-l6mkjh) ([raw file](https://github.com/waterloo-rocketry/canlib/blob/98710edd4997fb3cb428231661d772a8fae89ead/can_common.c#L409)):*
> ```C
> }
> 
> bool build_radi_info_msg(uint32_t timestamp,
> ```

rename
___
*[`can_common.c` line 411 at r2](https://reviewable.io/reviews/waterloo-rocketry/canlib/50#-NYBYH3n5WD3EafFMTH0:-NYBYH3n5WD3EafFMTH1:b-6vhzs5) ([raw file](https://github.com/waterloo-rocketry/canlib/blob/98710edd4997fb3cb428231661d772a8fae89ead/can_common.c#L411)):*
> ```C
> bool build_radi_info_msg(uint32_t timestamp,
>                          uint8_t sensor_identifier,
>                          uint16_t adc_value,
> ```

should it not be 32 bits?
___
*[`message_types.h` line 110 at r2](https://reviewable.io/reviews/waterloo-rocketry/canlib/50#-NYBYRsM3p5bQf84BJ7f:-NYBYRsM3p5bQf84BJ7g:b-2ufqxz) ([raw file](https://github.com/waterloo-rocketry/canlib/blob/98710edd4997fb3cb428231661d772a8fae89ead/message_types.h#L110)):*
> ```objc
>  * FILL_LVL:        TSTAMP_MS_H TSTAMP_MS_M TSTAMP_MS_L FILL_LEVEL            DIRECTION        None               None             None
>  *
>  * STATE_EST:     TSTAMP_MS_H TSTAMP_MS_M TSTAMP_MS_L KALMAN_H       KALMAN_MH  KALMAN_ML    KALMAN_L  KALMAN_ID
> ```

make comment line up

**Review by PCModeActivate — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/canlib/50)* status: all files reviewed, 5 unresolved discussions (waiting on @Joe-Joe-Joe-Joe and @KavinSatheeskumar)

___
*[`can_common.c` line 409 at r2](https://reviewable.io/reviews/waterloo-rocketry/canlib/50#-NYBYAGH9BUdL1_93oiD:-NYBeaR42YApbwoDHp6y:b-tpe6ri) ([raw file](https://github.com/waterloo-rocketry/canlib/blob/98710edd4997fb3cb428231661d772a8fae89ead/can_common.c#L409)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

rename
</blockquote></details>

gone now, dont need it, msg is built in kalman main.c instead
___
*[`message_types.h` line 110 at r2](https://reviewable.io/reviews/waterloo-rocketry/canlib/50#-NYBYRsM3p5bQf84BJ7f:-NYBepK_156tV58KH5Sl:bpz5zt5) ([raw file](https://github.com/waterloo-rocketry/canlib/blob/98710edd4997fb3cb428231661d772a8fae89ead/message_types.h#L110)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

make comment line up
</blockquote></details>

It does
___
*[`mcp2515/mcp_2515.h` line 124 at r1](https://reviewable.io/reviews/waterloo-rocketry/canlib/50#-NXwpP2q6xVzguaIzo1P:-NYBfFqZ0RuYj-HWnpZF:btz5wyu) ([raw file](https://github.com/waterloo-rocketry/canlib/blob/f872ef10293cd4b558a120099ba72ae6873633ff/mcp2515/mcp_2515.h#L124)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

What is going on here? Why are you commenting
</blockquote></details>

Should be uncommented now

**Review by KavinSatheeskumar — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/canlib/50#-:-NYBmz3lAksh_zYp7Asj:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Joe-Joe-Joe-Joe)

**Review by KavinSatheeskumar — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/canlib/50#-:-NYBrG5n8GcybscxYFy2:bnfp4nl)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @PCModeActivate)

**Pull request merged**
